# Generated by Django 3.2.14 on 2022-09-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
