# Generated by Django 3.2.14 on 2022-09-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_actual',
            field=models.BooleanField(default=True),
        ),
    ]
