# Generated by Django 3.2.14 on 2022-09-15 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0002_product_description'),
        ('purchase', '0004_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_shop.product'),
        ),
    ]
