# Generated by Django 3.2.14 on 2022-09-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_alter_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN PROCESSING', 'In processing'), ('CANCELLED', 'Cancelled'), ('DONE', 'Done')], default='IN PROCESSING', max_length=13),
        ),
    ]
