# Generated by Django 3.2.14 on 2022-10-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_orderreturn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
